loginreg/apps/logreg_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
        url(r'^$', views.index, name="index"),
        url(r'^register$', views.register),
        url(r'^display$', views.display, name="display"),
        url(r'^login$', views.login),
        url(r'^add$', views.add, name="add"),
        url(r'^create$', views.create, name="create"),
        #url(r'^show$', views.show, name='show'),
        url(r'^info$', views.create, name="info"),
        url(r'^join/(?P<trip_id>\d+)$', views.join, name='join'),
        url(r'^leave/(?P<trip_id>\d+)$', views.leave, name='leave'),
        url(r'^info/(?P<trip_id>\d+)$', views.info, name='info'),
        url(r'^logout$', views.logout, name="logout"),
]

loginreg/loginreg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.logreg_app.urls', namespace="users")),
]

loginreg/apps/logreg_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class UserManager(models.Manager):
    def registration_validation(self, data):
        errors = {}
        if len(data['name']) < 2:
            errors["name"] = "Name needs to be at least 2 characters"

        if len(data['alias']) < 2:
            errors["alias"] = "Alias needs to be at least 2 characters"

        if len(data['password']) < 8:
            errors["password"] = "Password needs to be at least 8 characters"
        
        if not data['password'] == data['confirm']:
            errors["password"] = "Passwords do not match"
        return errors

    def user_validation(self,data):
        errors = {}
        
        existing_user = User.objects.filter(email_address = data['email'])

        if len(existing_user) < 1:
            errors["email"] = "Email does not match our records"

        else:
            print existing_user
            print existing_user[0]
            print existing_user[0].password
            if data['password'] != existing_user[0].password:
                errors["password"] = "Password does not match our records for that email"
        return errors

class User(models.Model):
    name= models.CharField(max_length = 255)
    alias = models.CharField(max_length = 255)
    email_address = models.CharField(max_length = 255, unique = True)
    password = models.CharField(max_length = 255)
    # dob = models.DateField(verbose_name=None)
    # message = models.CharField(max_length = 255)
    objects = UserManager()

# Create your models here.
class Trip_CreatedManager(models.Manager):
    def trip_validation(self, data):
        errors = {}
        if len(data['destination']) < 2:
            errors["destination"] = "Your destination cannot be blank. We cannot send you on a trip to nowhere."
        if len(data['description']) < 2:
            errors["description"] = "Your plans cannot be blank. You must tell us what you're doing."
        return errors
class Trip_Created(models.Model):
    destination = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    travel_start = models.DateTimeField(auto_now=True)
    travel_end = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, related_name='created_trips')
    joined_by = models.ManyToManyField(User, related_name='trips_joined')
    objects = Trip_CreatedManager()
    def travellers(self):
        return self.joined_by.exclude(id=self.created_by.id)
    def __repr__(self):
        return "{}, {} ".format(self.destination, self.description)

loginreg/apps/logreg_app/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import *
from django.core.urlresolvers import reverse
from django.contrib import messages

def index(request):
    return render(request, 'logreg_app/index.html')

def register(request):
    errors = User.objects.registration_validation(request.POST)
    if len(errors): #there are errors
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    else:
        person = User.objects.create(
        name = request.POST['name'],
        alias = request.POST['alias'],
        password = request.POST['password'],
        email_address = request.POST['email'])
        request.session['name'] = request.POST['name']
        request.session['id'] = person.id
        return redirect ('/display')

def login(request):
    errors = User.objects.user_validation(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    else:
        logged_in_user = User.objects.get(email_address=request.POST['email'])
        print logged_in_user
        request.session['name'] = logged_in_user.name
        request.session['id'] = logged_in_user.id
        return redirect ('/display')

def display(request):
    context = {
        'users' :User.objects.all(),
        'trips' : Trip_Created.objects.filter(joined_by=User.objects.get(id=request.session['id'])),
        'other_trips': Trip_Created.objects.exclude(joined_by=User.objects.get(id=request.session['id']))
    }
    return render(request, 'logreg_app/display.html', context)

def logout(request):
    request.session.clear()
    return redirect ('/')
# Create your views here.

def add(request):
    return render(request, 'logreg_app/add_trip.html')

def create(request):
    if request.method == 'POST':
        errors = Trip_Created.objects.trip_validation(request.POST)
        if len(errors):  # if there's errors -- see models.py for error list!
            for tag, error in errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('users:add'))
        else:
            user = User.objects.get(id=request.session['id'])
            trip = Trip_Created.objects.create(
                destination = request.POST['destination'],
                description = request.POST['description'],
                travel_start = request.POST['travel_start'],
                travel_end = request.POST['travel_end'],
                created_by=user
            )
            trip.joined_by.add(user)
            trip.save()
            return redirect(reverse('users:display'))
    else:
        return redirect(reverse('users:display'))

# def show(request, user_id):
#     context = {
#         'trip' : Add_trip.objects.get(id=user_id)
#     }
#     return render(request, 'logreg_app/display.html', context)

def join(request, trip_id):
    user = User.objects.get(id=request.session['id'])
    trip = Trip_Created.objects.get(id=trip_id)
    trip.joined_by.add(user)
    trip.save()
    return redirect('/display')


def leave(request, trip_id):
    user = User.objects.get(id=request.session['id'])
    trip = Trip_Created.objects.get(id=trip_id)
    trip.joined_by.remove(user)
    trip.save()
    return redirect('/display')

def info(request, trip_id):
    trip = Trip_Created.objects.get(id=trip_id)
    context = {

        'trip': trip,
        'other_users' : User.objects.exclude(created_trips__created_by=trip.created_by)
    }
    return render(request, 'logreg_app/destination.html', context)

loginreg/apps/logreg_app/templates/logreg_app/add_trip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Trip</title>
</head>
<body>
    <h1>Planning Your Dream Vacation!!</h1>
    <h4>No Payment Required!!!</h4>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif%}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    <form action="{% url 'users:create' %}" method="POST">
        {% csrf_token%} 
        <p>Destination:</p>
        <input type="text" name="destination">
        <p>Description:</p>
        <input type="text" name="description">
        <p>Travel Date From:</p>
        <input type="date" name="travel_start">
        <p>Travel Date To:</p>
        <input type="date" name="travel_end">
        <input type="submit" value="Start Tripping">
    </form>
    <br>
    <br>
    
    <a href="{% url 'users:display' %}"><button>TAKE ME HOME</button></a>
    <a href="{% url 'users:index' %}"><button>RUN AWAY!!!!</button></a>
</body>
</html>

loginreg/apps/logreg_app/templates/logreg_app/destination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'exam_app/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <title>Destination</title>
</head>
<body>
    <h1>This is Why I, {{request.session.name}}, Picked {{trip.destination}} </h1>
  
    <p>Planned by: {{trip.created_by.name}}</p>
    <p>This is what you may be joining: {{trip.description}}</p>
    <p>I will be leaving on:{{trip.travel_start}}</p>
    <p>I will be back home on: {{trip.travel_end}}</p>

    <h1>PLEASE JOIN ME!!!! (I hate traveling alone)</h1>
    {%for user in trip.travellers %}
        <p>{{user.name}}</p>
        {% endfor %}


    <a href="{% url 'users:display' %}">Home</a>
    <a href="{% url 'users:index' %}">Logout</a>
</body>
</html>

loginreg/apps/logreg_app/templates/logreg_app/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'logreg_app/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <title>Exam</title>
</head>
<style>
    thead, th, td, tr{
        border: 3px solid black;
        border-collapse: collapse;
        padding: 3px;
        font-size: 26px;
    }
</style>
<body>
    <h1>Welcome {{request.session.name}}</h1>
    <a href={% url 'users:logout' %}>Cancel My Trip</a>
    
    <h2>Your Trips Scheduled:</h2>
    <table>
        <thead>
            <tr>
                <td>Destination:</td>
                <td>Travel Start Date:</td>
                <td>Travel End Date:</td>
                <td>Please creep on my plans:</td>
                <td>I'm over this trip -- GOODBYE</td>
            </tr>
        </thead>
        {% for trip in trips %}
        <tr>
            <td><a href="/info/{{ trip.id }}">{{ trip.destination }}</a></td>
            <td>{{ trip.travel_start }}</td>
            <td>{{ trip.travel_end }}</td>
            <td>{{ trip.description }}</td> 
            <td><a href="/leave/{{trip.id}}">Leave</a></td>
        </tr>
        {% endfor %}
    </table>

    <h2>Other User's Travel Plans: </h2>
    <table>
        <thead>
            <tr>
                <td>Name:</td>
                <td>Destination:</td>
                <td>Travel Start Date:</td>
                <td>Travel End Date:</td>
                <td>Join?????</td>
            </tr>
        </thead>
        {% for trip in other_trips %}
        <tr>
            <td>{{trip.created_by.name}}</td>
            <td><a href="/info/{{ trip.id }}">{{ trip.destination }}</a></td>
            <td>{{ trip.travel_start }}</td>
            <td>{{ trip.travel_end }}</td>
            <td><a href="/join/{{ trip.id }}">Join</a></td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <br>
    <a href="{% url 'users:add' %}"><button>START PLANNING YOUR DREAM VACATION HERE!!</button></a>
</body>

</html>

loginreg/apps/logreg_app/templates/logreg_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'logreg_app/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <title>Welcome</title>
</head>
<body>
    <h1>Welcome</h1>
    {% if messages %}
    <ul>
        {% for error in messages %}
           <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <div id="table1">
        <h4>Register</h4>
        <form action="/register" method="post">
            {% csrf_token %}
            Name:<input type="text" name="name" id=""><br>
            Alias:<input type="text" name="alias" id=""><br>
            Email:<input type="email" name="email" id=""><br>
            Password:<input type="password" name="password" id=""><br>
            <p>*Password should be at least 8 characters</p>
            Confirm Password:<input type="password" name="confirm" id=""><br>
            Date of Birth:<input type="date" name="date" id="cal">
            <input type="submit" value="Register">
        </form>
    </div>
    <div id="table2">
        <h4>Login</h4>
        <form action="/login" method="post">
            {% csrf_token %}
            Email: <input type="email" name="email" id=""> <br>
            Password: <input type="password" name="password" id=""> <br>
            <input type="submit" value="Log In">
        </form>
    </div>
</body>
</html>